var PROMISE_PENDING_SUFFIX = '@@PENDING';
var PROMISE_FULFILLED_SUFFIX = '@@FULFILLED';
var PROMISE_REJECTED_SUFFIX = '@@REJECTED';

var keyFulfilled = 'fulfilled';
var keyRejected = 'rejected';
var keyPending = 'pending';
var SHORT_SUFFIX_LIST = [keyFulfilled, keyRejected, keyPending];
var SHORT_SUFFIX_MAP = {};
SHORT_SUFFIX_MAP[keyFulfilled] = PROMISE_FULFILLED_SUFFIX;
SHORT_SUFFIX_MAP[keyRejected] = PROMISE_REJECTED_SUFFIX;
SHORT_SUFFIX_MAP[keyPending] = PROMISE_PENDING_SUFFIX;

module.exports = {
    PROMISE_PENDING_SUFFIX: PROMISE_PENDING_SUFFIX,
    PROMISE_FULFILLED_SUFFIX: PROMISE_FULFILLED_SUFFIX,
    PROMISE_REJECTED_SUFFIX: PROMISE_REJECTED_SUFFIX,

    SHORT_SUFFIX_LIST: SHORT_SUFFIX_LIST,
    SHORT_SUFFIX_MAP: SHORT_SUFFIX_MAP
};